### ISSUE TITLE
REST API docs some headings not displaying correctly

### ISSUE THREAD

**Issue by prufrock** [ory/docusaurus-template#47]
Hello!

In the documentation for the [REST API](https://www.ory.sh/keto/docs/reference/api/) some of the headings are showing their hash signs. For instance the parameters heading is "##### Parameters".

Thanks,

David

**Comment by aeneasr** [comment]
@vinckr can you help fix this? I can help you if you need help

**Comment by aeneasr** [comment]
https://github.com/ory/docusaurus-template/issues/48#issuecomment-706747643
