### ISSUE TITLE
add default file creation via make

### ISSUE THREAD

**Issue by zepatrik** [ory/docusaurus-template#8]
as outlined in #7

**Comment by aeneasr** [comment]
I don't think we really need this. The current pipeline works pretty well IMO!

**Comment by zepatrik** [comment]
Currently one still has to create the 4 files manually as described in the readme?

**Comment by aeneasr** [comment]
The effort is not worth it, last time we created a new documentation was in 2019. It's ok to copy a few files :)

**Comment by zepatrik** [comment]
Think it was May 18 as I fixed the README at that point :wink: but never mind, it is an easy workaround
